#pragma once

#include <iostream>
#include <cstdint>
#include <filesystem>
#include <functional>
#include <string>
#include <string_view>
#include <vector>
#include <concepts>
#include <cstdint>
#include <string>
#include <string_view>
#include <vector>
#include <atomic>
#include <condition_variable>
#include <exception>
#include <functional>
#include <memory>
#include <mutex>
#include <queue>
#include <set>
#include <thread>
#include <vector>
#include <chrono>
#include <cstdint>
#include <memory>
#include <string>
#include <cstdint>
#include <memory>
#include <vector>
#include <cstdint>
#include <numbers>
#include <type_traits>
#include <ostream>
#include <iomanip>
#include <sstream>
#include <filesystem>
#include <stdexcept>
#include <string>
#include <cmath>
#include <filesystem>
#include <iostream>
#include <fstream>

#include <date/date.h>
#include <glad/gl.h>
#include <GLFW/glfw3.h>
#include <stb/stb_image.h>
#include <termcolor/termcolor.hpp>
